---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[selinux]
      - recipe[ulimit]
      - recipe[hdpcluster::default]
      - recipe[java]
      - recipe[hdpcluster::docker]
      - recipe[hdpcluster::nginx]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: { 'fqdn': 'test.test.org', 'java':
      { 'install_flavor': 'oracle', 'jdk_version': '8', 'oracle': {'accept_oracle_download_terms':true} },  'selinux':
      { 'status': 'permissive'}, 'ulimit':
      { 'users': { 'hdpuser': {'filehandle_limit': '8193'} } } }
